# Generated by Django 3.2.5 on 2021-07-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slid', models.ImageField(upload_to='Slider')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
