# Generated by Django 3.2.5 on 2021-07-27 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210727_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sub_categroy',
        ),
        migrations.DeleteModel(
            name='sub_categroy',
        ),
    ]
