# Generated by Django 3.2.5 on 2021-07-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210730_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_address',
            name='mobile',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
